#pragma config(Sensor, dgtl1,  intakeButton,   sensorTouch)
#pragma config(Sensor, dgtl2,  changeDirectionButton, sensorTouch)
#pragma config(Sensor, dgtl3,  forwardLED,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  reverseLED,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, clawButton,     sensorTouch)
#pragma config(Motor,  port1,           intakeMotor,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          clawMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {

		int direction = (SensorValue[changeDirectionButton] > 0 ? +1 : -1);
		if (direction > 0) {
			SensorValue[forwardLED] = 1;
			SensorValue[reverseLED] = 0;
		} else {
			SensorValue[forwardLED] = 0;
			SensorValue[reverseLED] = 1;
		}

		if (SensorValue[intakeButton] > 0) {
			motor[intakeMotor] = 127 * direction;
		} else {
		  motor[intakeMotor] = 0;
		}

		if (SensorValue[clawButton] > 0) {
			motor[clawMotor] = 127 * direction;
		} else {
		  motor[clawMotor] = 0;
		}
	}
}
