#pragma config(Motor,  port2,           driveRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           angleRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           driveLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           angleLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           pickUpLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           pickUpRight,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (1==1)
	{
		//Motors 2 and 4 are drive motors
		//Motors 3 and 5 are motors that drive the motors that pick up the ball

    	motor[port2]= -vexRT[Ch2];
    	motor[port4] = vexRT[Ch2];
    	motor[port2]= vexRT[Ch4];
    	motor[port4] = vexRT[Ch4];
    	if(vexRT[Btn7U]==1)
    	{
    		motor[port3] = -120;
    		motor[port5] = 120;
    	}
    	else
    	{
    	motor[port3] = 0;
    	motor[port5] = 0;
  	  }
    	if(vexRT[Btn7D]==1)
    	{
    	 	motor[port3] = 120;
    		motor[port5] = -120;
    	}
    	else
    	{
    		motor[port3] = 0;
    		motor[port5] = 0;
  	  }
      //motor[centerWheel] = vexRT[Ch1];

    	/*
    	if(vexRT[Btn7U]==1)
       {
      	motor[port2]=-127;
      	motor[port4]=-127;
       }
      else
       {
      	motor[port2]=0;
      	motor[port4]=0;
       }
      if(vexRT[Btn7D]==1)
       {
      	motor[port5]=127;
      	motor[port4]=127;
       }
      else
       {
      	motor[port5]=0;
      	motor[port4]=0;

       }
       */
    }
}
