#pragma config(Motor,  port2,           frontWheelR,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontWheelL,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backWheelR,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backWheelL,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armbase,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int X2 = 0, Y1 = 0, X1 = 0, threshold = 15;
	while (1 == 1) {
		if(vexRT[Btn8D] == 1) {
			motor[port6] = 127;
			} else if(vexRT[Btn8U] == 1) {
			motor[port6] = -127;
			} else {
			motor[port6] = 0;
		}
		if(vexRT[Btn7D] == 1) {
			motor[port7] = 127;
			} else if(vexRT[Btn7U] == 1) {
			motor[port7] = -127;
			} else {
			motor[port7] = 0;
		}
		if(vexRT[Btn8L] == 1) {
			motor[port8] = 127;
			} else if(vexRT[Btn8R] == 1) {
			motor[port8] = -127;
			} else {
			motor[port8] = 0;
		}


		//Create "deadzone" for Y1/Ch3
		if(abs(vexRT[Ch3]) > threshold)
			Y1 = vexRT[Ch3];
		else
			Y1 = 0;
		//Create "deadzone" for X1/Ch4
		if(abs(vexRT[Ch4]) > threshold)
			X1 = vexRT[Ch4];
		else
			X1 = 0;
		//Create "deadzone" for X2/Ch1
		if(abs(vexRT[Ch1]) > threshold)
			X2 = vexRT[Ch1];
		else
			X2 = 0;

		//Remote Control Commands
		motor[port2] = Y1 - X2 - X1;
		motor[port3] =  Y1 - X2 + X1;
		motor[port4] = Y1 + X2 + X1;
		motor[port5] =  Y1 + X2 - X1;
	}
}
