#pragma config(Motor,  port2,           topLift,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           claw,          tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           leftMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           rightMotor,    tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           bottomLift,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
///////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
 startMotor(port4);
 startMotor(port5);
 wait(5);
 stopMotor(port4);
  stopMotor(port4)
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  motor[port4]=vexRT(Ch2);
		motor[port5]=vexRT(Ch3);
		motor[port2]=vexRT(Ch4);
		motor[port3]=vexRT(Ch1);
		if(Btn6U==1){
			motor[port9]=127;
		}else{
		if(Btn6D==1){
				motor[port9]=-127;
			}else{
				motor[port9]=0;
			}
	}

			}


}
