#pragma config(Sensor, dgtl1,  bump,           sensorTouch)
#pragma config(Motor,  port2,           leftmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightmotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		// While the bump sensor is held down, activate the left motor
		if(SensorValue[bump] == 1) {
			motor[leftmotor] = 127;
			} else {
			motor[leftmotor] = 0;
		}

		motor[rightmotor]  = vexRT[Ch3];


	}
}
