#pragma config(Sensor, dgtl1,  bump,           sensorTouch)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
        // The threshold is used to control the sensitivity of the analog sticks.
        // We ensure that we don't send a value which is too small to the motors.
        int threshold = 10;

        // The driving mode: tankControl (0) or arcadeControl (1).
        int mode = 0;

        // Press this button to switch modes.
        int modeButton = Btn5U;

        while(true){
                // While the bump sensor is held down, activate the left motor
                //if(SensorValue[bump] == 1) {
                //	motor[leftMotor] = 127;
                //} else {
                //	motor[leftMotor] = 0;
                //}

                // Tank drive with thresholding.
                //
                // Superceded by the built-in tankControl() function.
                //
                //if (vexRT[Ch3] > threshold ||  vexRT[Ch3] < -threshold) {
                //	motor[leftMotor] = vexRT[Ch3];
                //}
                //if (vexRT[Ch2] > threshold || vexRT[Ch2] < -threshold) {
                //	motor[rightMotor] = vexRT[Ch2];
                //}

                if (vexRT[modeButton] == 1) {
                        // Mode change: Intentionally stop and sleep briefly.
                  motor[leftMotor] = 0;
                  motor[rightMotor] = 0;
                  sleep(500);
                  mode = 1 - mode;
                }

                if (mode == 0) {
                        // Tank drive with threshold.
                        tankControl(Ch4, Ch3, threshold); // Left joystick, OR
                        // tankControl(Ch2, Ch1, threshold); // Right joystick
                } else if (mode == 1) {
                  // Single joystick drive with threshold.
                        arcadeControl(Ch4, Ch3, threshold); // Left joystick, OR
                        // arcadeControl(Ch2, Ch1, threshold); // Right joystick
                }


                clearLCDLine(0);
                clearLCDLine(1);
                displayLCDNumber(0, 0, mode, 4);
                displayLCDNumber(1, 5, threshold, 4);

        } // end (while true)
} // end (task main)
