#pragma config(Motor,  port1,           BackLeft,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FrontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ElbowRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           ElbowLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ShoulderRight, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           ShoulderLeft,  tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          BackRight,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int speed = 127;
task main()
{
	while(1 == 1)
	{
		//Right side of the robot is controlled by the right joystick, Y-axis
		motor[FrontRight] = vexRT[Ch2];
		motor[BackRight]  = vexRT[Ch2];
		//Left side of the robot is controlled by the left joystick, Y-axis
		motor[FrontLeft] = vexRT[Ch3];
		motor[BackLeft]  = vexRT[Ch3];
	}
  //Arm Control
	//Shoulder Motor
    if(vexRT[Btn6U] == 1)
    {
      motor[ShoulderLeft] = speed;
      motor[ShoulderRight] = speed;
    }
    else if(vexRT[Btn6D] == 1)
    {
      motor[ShoulderLeft] = -speed;
      motor[ShoulderRight] = -speed;
    }
    else
    {
      motor[ShoulderLeft] = 0;
      motor[ShoulderRight] = 0;
    }

    //Elbow Control
       if(vexRT[Btn5U] == 1)
    {
      motor[ElbowLeft] = speed;
      motor[ElbowRight] = speed;
    }
    else if(vexRT[Btn5D] == 1)
    {
      motor[ElbowLeft] = - speed;
      motor[ElbowRight] = - speed;
    }
    else
    {
      motor[ElbowLeft] = 0;
      motor[ElbowRight] = 0;
    }

}
