#pragma config(Motor,  port1,           BackLeft,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FrontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ElbowRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           ElbowLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ShoulderRight, tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           ShoulderLeft,  tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          BackRight,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[ShoulderRight] = -127;
	sleep(1000);

}
