#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           foo,           tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port2,           foo2,          tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port3,           foo3,          tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speed = 63;
	int margin = 10;

	nMotorEncoder[port1] = 0;
	nMotorEncoder[port2] = 0;
	nMotorEncoder[port3] = 0;


	//motor[port1] = -127;
	//motor[port2] = -127;
	//motor[port3] = -127;
	while(true) {
		if(abs(nMotorEncoder[port3]) < abs(nMotorEncoder[port2])) {
			motor[port3] = speed + margin;
			motor[port2] = speed;
		}
		else if (abs(nMotorEncoder[port2]) < abs(nMotorEncoder[port3])) {
			motor[port3] = speed;
			motor[port2] = speed + margin;
		}
		else {
			motor[port3] = speed;
			motor[port2] = speed;
		}
	}
}
