#pragma config(Motor,  port2,           RightArm,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftArm,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	float velocity = 0;
	float acceleration = 4.5;

	while (1==1) {
		if (vexRT[Btn8R] > 0) {
			//User trying to raise arm up.
			velocity += acceleration;
			if (velocity > 127) {
				velocity = 127;
			}

		} else if (vexRT[Btn8D] > 0){
			//User trying to lower arm.
			velocity -= acceleration;
			if (velocity < -127) {
				velocity = -127;			velocity -= acceleration;

			}

		} else {
			// The user is not holding any key down.  Decay the arm velocity toward 0.
			if (velocity > 0) {
				velocity -= 0.5 * acceleration;
			} if (velocity < 0) {
				velocity += 0.5 * acceleration;
			}
		}
		//Assign current velocity to the motors
		motor[RightArm] = velocity;
		motor[LeftArm] = velocity;

	}


}
