#pragma config(Sensor, dgtl11, toggleMotors,   sensorTouch)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	clearTimer(timer1);
	bool motorsOn = true;
	while(true){
		if (motorsOn){
			if(time1[timer1] == 0)
			{
				motor[port3] = 100;
			}
			else if(time1[timer1] > 5000)
			{
				motor[port3] = 0;
			}

			if(time1[timer1] >= 5000)
			{
				motor[port2] = -100;
			}

		}
		if (SensorValue[toggleMotors] == true && time1[timer2] > 1000)
		{
			clearTimer(timer2);
			motorsOn = !motorsOn;
		}

		//We dont allow the timer to run for more than a 1000 millseconds because the timer auto-restets after 32,000 millseconds
		if (time1[timer1] > 5500)
		{
			motor[port2] = 0;
			clearTimer(timer1);
		}
	}


}
