#pragma config(Sensor, dgtl1,  pin1,           sensorTouch)
#pragma config(Sensor, dgtl2,  pin2,           sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

int speed();
int accelP();
int accelN();
void stopMotors();
void subname();
void tankControl();

void accelerometerControl();

int threshold = 20;   // helps to eliminate 'noise' from a joystick that isn't perfectly at (0,0)
int accel_x   = 0;      // Will hold the controller-accelerometer X reading.
int accel_y   = 0;      // Will hold the controller-accelerometer Y reading.
int prev_x    = 0;      // Will hold the previous accelerometer X reading (for comparison).
int prev_y    = 0;      // Will hold the previous accelerometer Y reading (for comparison).
int joy_x;            // will hold the X value of the analog stick (choices below)
int joy_y;            // will hold the Y value of the analog stick (choices below)
/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		if ( SensorValue(pin1) == 1)
		{
			accelerometerControl();
		}
		else if ( SensorValue(pin2) == 1)
		{
			subname();
		}
		else
		{
			tankControl();
		}
	}
}

int speed()
{
	if (vexRT[Btn6U] == 1)
	{
		return 1;
	}
	else if (vexRT[Btn5U] == 1)
	{
		return 3;
	}
	else
	{
		return 2;
	}
}

int accelP()
{
	return ((-1 * vexRT[AccelY]) + vexRT[AccelX]);
}

int accelN()
{
	return ((-1 * vexRT[AccelY]) - vexRT[AccelX]);
}

void stopMotors()
{
	motor[leftMotor]  = 0;
	motor[rightMotor] = 0;
}

void subname()
{
	joy_x = vexRT[Ch4];   // This is the RIGHT analog stick.  For LEFT, change 'Ch1' to 'Ch4'.
	joy_y = vexRT[Ch3];   // This is the RIGHT analog stick.  For LEFT, change 'Ch2' to 'Ch3'.

	// Forward, and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is POSITIVE)
	if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y > 0))
	{
		motor[leftMotor]  = (joy_y + joy_x)/speed();
		motor[rightMotor] = (joy_y - joy_x)/speed();
	}
	// Backwards and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is NEGATIVE)
	else if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y < 0))
	{
		motor[leftMotor]  = (joy_y - joy_x)/speed();
		motor[rightMotor] = (joy_y + joy_x)/speed();
	}
	// Turning in place: (abs(X) is above the threshold, abs(Y) is below the threshold)
	else if((abs(joy_x) > threshold) && (abs(joy_y) < threshold))
	{
		motor[leftMotor]  = joy_x;
		motor[rightMotor] = (-1 * joy_x);
	}
	// Standing still: (both abs(X) and abs(Y) are below the threshold)
	else
	{
		motor[leftMotor]  = 0;
		motor[rightMotor] = 0;
	}
}

void tankControl()
{
	if(abs(vexRT[Ch3]) > threshold)         // If the left joystick is greater than or less than the threshold:
	{
		motor[leftMotor]  = (vexRT[Ch3])/speed();   // Left Joystick Y value / 2.
	}
	else                                    // If the left joystick is within the threshold:
	{
		motor[leftMotor]  = 0;                // Stop the left motor (cancel noise)
	}

	if(abs(vexRT[Ch2]) > threshold)         // If the right joystick is greater than or less than the threshold:
	{
		motor[rightMotor] = (vexRT[Ch2])/speed();   // Right Joystick Y value / 2.
	}
	else                                    // If the right joystick is within the threshold:
	{
		motor[rightMotor] = 0;                // Stop the right motor (cancel noise)
	}
}

void accelerometerControl()
{
	prev_x = accel_x;           // update previous x reading to 'accel_x'
	prev_y = accel_y;           // update previous y reading to 'accel_y'
	accel_x = vexRT[AccelX];    // update 'accel_x' to new current reading
	accel_y = vexRT[AccelY];    // update 'accel_y' to new current reading

	// is abs(current - prev) < threshold?
	if( (abs(accel_x - prev_x) < threshold) || (abs(accel_y - prev_y) > threshold) )
	{
		// YES.
		// Are either of them over the 'noise' threshold?
		if( (abs(accel_x) > threshold) || (abs(accel_y) > threshold) )
		{
			// YES.
			if(accel_y > 0) // going backwards?
			{
				motor[leftMotor]  = accelN()/speed();
				motor[rightMotor] = accelP()/speed();
			}
			else  // going forward, or point turn:
			{
				motor[leftMotor]  = accelP()/speed();
				motor[rightMotor] = accelN()/speed();
			}
		}
		// NO - give no power to motors, joystick is in center position (or near enough to it)
		else
		{
			stopMotors();
		}
		// NO - make no changes.
	}
	wait1Msec(20);      // the VEXnet controller updates every 15ms or so
}
